export const LEGAL_SECTIONS = [
  {
    id: 'international-treaties',
    number: '01',
    titleZh: '国际条约',
    titleEn: 'INTERNATIONAL TREATIES',
    summaryZh: '国家责任、空间物体身份、管辖控制与损害赔偿的基础框架。',
    summaryEn: 'The foundation for state responsibility, identification, jurisdiction, control, and liability.',
  },
  {
    id: 'mitigation-rules',
    number: '02',
    titleZh: '碎片减缓规则',
    titleEn: 'DEBRIS MITIGATION RULES',
    summaryZh: '联合国指南、机构间指南、技术标准和机构要求如何减少新的碎片。',
    summaryEn: 'How UN guidance, inter-agency guidelines, standards, and agency requirements reduce new debris.',
  },
  {
    id: 'regulation',
    number: '03',
    titleZh: '国内与区域监管',
    titleEn: 'NATIONAL & REGIONAL REGULATION',
    summaryZh: '国际原则如何通过许可证、国内法规和区域立法转化为可执行要求。',
    summaryEn: 'How international principles become enforceable through licensing, national rules, and regional legislation.',
  },
  {
    id: 'governance-gaps',
    number: '04',
    titleZh: '治理缺口',
    titleEn: 'GOVERNANCE GAPS',
    summaryZh: '为什么规则已经很多，历史碎片清理、授权、追责和跨国执行仍然困难。',
    summaryEn: 'Why cleanup, authorization, attribution, and cross-border enforcement remain difficult despite extensive rules.',
  },
  {
    id: 'conclusion',
    number: '05',
    titleZh: '法律结论',
    titleEn: 'LEGAL TAKEAWAYS',
    summaryZh: '现有法律已经解决什么，以及全球碎片治理仍缺少什么。',
    summaryEn: 'What current law already addresses and what global debris governance still lacks.',
  },
  {
    id: 'sources',
    number: '06',
    titleZh: '官方来源',
    titleEn: 'OFFICIAL SOURCES',
    summaryZh: '本板块使用的条约、指南、标准、机构政策和监管文件官方入口。',
    summaryEn: 'Official treaty, guideline, standard, agency-policy, and regulatory sources used in this section.',
  },
]

const source = (labelZh, labelEn, url) => ({ labelZh, labelEn, url })

export const LEGAL_DOSSIERS = [
  {
    id: 'outer-space-treaty-responsibility',
    number: '01',
    section: 'international-treaties',
    year: '1967',
    tabTitleZh: '国家与商业航天责任',
    tabTitleEn: 'State Responsibility',
    typeLabelZh: '国际条约｜对缔约国具有法律约束力',
    typeLabelEn: 'INTERNATIONAL TREATY · BINDING ON PARTIES',
    titleZh: '《外层空间条约》：国家对商业航天活动仍负有责任',
    titleEn: 'Outer Space Treaty: States Remain Responsible for Private Space Activities',
    bodyZh: [
      '1967 年《外层空间条约》是国际空间法最基础的条约之一。第 VI 条规定，缔约国要对本国在外层空间开展的活动承担国际责任，无论实际执行者是政府机构还是私人企业。',
      '私人公司开展空间活动，需要得到有关国家的授权并接受持续监督。因此，一颗商业卫星进入太空后，并不会因为运营者是企业就脱离国家责任体系。',
    ],
    bodyEn: [
      'The 1967 Outer Space Treaty is one of the foundations of international space law. Article VI states that States Parties bear international responsibility for national activities in outer space, whether those activities are carried out by governmental agencies or non-governmental entities.',
      'Private space activities require authorization and continuing supervision by the appropriate State. A commercial satellite therefore does not fall outside the state-responsibility framework simply because it is privately operated.',
    ],
    highlightZh: '私人公司进入太空，不意味着国家责任消失。',
    highlightEn: 'Private space activity does not make state responsibility disappear.',
    sourceLinks: [source('UNOOSA —《外层空间条约》', 'UNOOSA — Outer Space Treaty', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/outerspacetreaty.html')],
  },
  {
    id: 'outer-space-treaty-jurisdiction',
    number: '02',
    section: 'international-treaties',
    year: '1967',
    tabTitleZh: '报废卫星仍有归属',
    tabTitleEn: 'Defunct Ownership',
    typeLabelZh: '国际条约｜对缔约国具有法律约束力',
    typeLabelEn: 'INTERNATIONAL TREATY · BINDING ON PARTIES',
    titleZh: '《外层空间条约》第 VIII 条：报废卫星并非无主物',
    titleEn: 'Outer Space Treaty Article VIII: Defunct Does Not Mean Ownerless',
    bodyZh: [
      '空间物体失效以后，并不会因为“不再工作”就自动变成谁都可以处理的无主物。',
      '《外层空间条约》第 VIII 条规定，登记国对登记在册的空间物体继续保有管辖和控制；空间物体及其组成部分的所有权，也不会因为它位于外层空间或返回地球而自动改变。这使主动碎片清除不仅是工程问题，也涉及授权、所有权和国家间协调。',
    ],
    bodyEn: [
      'A space object does not automatically become ownerless simply because it is no longer functioning.',
      'Article VIII of the Outer Space Treaty provides that the State of registry retains jurisdiction and control over its registered space object. Ownership of space objects and their component parts is not automatically changed by their presence in outer space or by their return to Earth. Active debris removal therefore raises questions of authorization, ownership, jurisdiction, and international coordination as well as engineering.',
    ],
    highlightZh: '“已经报废”不等于“谁都可以拿走”。',
    highlightEn: '“Defunct” does not mean “free for anyone to remove.”',
    sourceLinks: [source('UNOOSA —《外层空间条约》', 'UNOOSA — Outer Space Treaty', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/outerspacetreaty.html')],
  },
  {
    id: 'liability-convention',
    number: '03',
    section: 'international-treaties',
    year: '1972',
    tabTitleZh: '空间损害责任',
    tabTitleEn: 'Space Liability',
    typeLabelZh: '国际条约｜对缔约国具有法律约束力',
    typeLabelEn: 'INTERNATIONAL TREATY · BINDING ON PARTIES',
    titleZh: '《责任公约》：地面损害与太空碰撞适用不同责任规则',
    titleEn: 'Liability Convention: Damage on Earth and Damage in Space Follow Different Rules',
    bodyZh: [
      '1972 年《空间物体所造成损害的国际责任公约》建立了空间物体造成损害后的赔偿框架。',
      '如果空间物体在地球表面或对飞行中的航空器造成损害，发射国原则上承担绝对责任。若损害发生在外层空间，例如一个国家的空间物体损害另一个国家的空间物体，则适用以过错为基础的责任规则。这套制度主要解决的是“损害已经发生以后如何追责和赔偿”，并不等同于建立了一个要求各国提前清除所有太空垃圾的制度。',
    ],
    bodyEn: [
      'The 1972 Liability Convention establishes a framework for compensation when space objects cause damage.',
      'A launching State is absolutely liable for damage caused by its space object on the surface of the Earth or to aircraft in flight. For damage caused elsewhere than on the surface of the Earth to another State’s space object, liability is based on fault. The Convention mainly addresses responsibility after damage occurs. It does not create a general global obligation requiring every State to remove all existing debris in advance.',
    ],
    highlightZh: '“造成损害后可能承担责任”不等于“法律已经规定谁必须提前把垃圾清走”。',
    highlightEn: 'Liability after damage is not the same as a universal duty to remove debris before an accident occurs.',
    sourceLinks: [source('UNOOSA —《责任公约》', 'UNOOSA — Liability Convention', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/introliability-convention.html')],
  },
  {
    id: 'registration-convention',
    number: '04',
    section: 'international-treaties',
    year: '1975',
    tabTitleZh: '空间物体登记',
    tabTitleEn: 'Registration',
    typeLabelZh: '国际条约｜对缔约国具有法律约束力',
    typeLabelEn: 'INTERNATIONAL TREATY · BINDING ON PARTIES',
    titleZh: '《登记公约》：确认空间物体的身份与登记国',
    titleEn: 'Registration Convention: Identifying Whose Object Is in Orbit',
    bodyZh: [
      '《登记公约》要求有关国家建立空间物体登记制度，并向联合国提供空间物体的基本信息。',
      '登记信息可以帮助确认空间物体的登记国、发射信息、基本轨道参数和一般功能，是识别空间物体和讨论责任的重要基础。但“能够确认它是谁的”与“法律自动要求它的所有者把它清走”仍然是两个不同的问题。',
    ],
    bodyEn: [
      'The Registration Convention requires relevant States to maintain registries of space objects and provide basic information to the United Nations.',
      'Registration information helps identify the State of registry, launch information, basic orbital parameters, and the general function of a space object. This provides an important foundation for identification and responsibility. However, identifying ownership or registration does not automatically create a universal cleanup obligation.',
    ],
    highlightZh: '登记可以帮助确认“它是谁的”，却不会自动产生全球统一的清理义务。',
    highlightEn: 'Registration can identify an object, but it does not automatically create a global duty to remove it.',
    sourceLinks: [source('UNOOSA —《登记公约》', 'UNOOSA — Registration Convention', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/introregistration-convention.html')],
  },
  {
    id: 'copuos-mitigation',
    number: '05',
    section: 'mitigation-rules',
    year: '2007',
    tabTitleZh: 'COPUOS 减缓准则',
    tabTitleEn: 'COPUOS Guidelines',
    typeLabelZh: '联合国指南｜非约束性',
    typeLabelEn: 'UN GUIDELINES · NON-BINDING',
    titleZh: 'COPUOS《空间碎片减缓准则》',
    titleEn: 'COPUOS Space Debris Mitigation Guidelines',
    bodyZh: [
      'COPUOS《空间碎片减缓准则》提出 7 项核心原则，包括减少正常任务中释放碎片、避免航天器和火箭级解体、降低碰撞风险，以及在任务结束后尽量减少物体长期占用受保护轨道区域。',
      '这些准则形成重要国际共识，但其本身属于非法律约束性指南，落实仍依赖国家法规、许可证、机构规则和运营者执行。',
    ],
    bodyEn: [
      'The UN Committee on the Peaceful Uses of Outer Space (COPUOS) Space Debris Mitigation Guidelines contain seven core guidelines. They address limiting debris released during normal operations, preventing break-ups, reducing collision risks, and limiting long-term interference with protected orbital regions after missions end.',
      'The guidelines have become an important international reference and are reflected in many national, agency, and technical frameworks. However, the guidelines themselves are non-binding. Their implementation depends on national regulation, licensing, agency requirements, and operator practice.',
    ],
    highlightZh: '它们代表国际共识，但本身不是一部可以直接对所有航天活动实施处罚的全球法律。',
    highlightEn: 'They represent international consensus, but they are not a single globally enforceable debris law.',
    sourceLinks: [source('UNOOSA — 空间碎片减缓准则', 'UNOOSA — Space Debris Mitigation Guidelines', 'https://www.unoosa.org/pdf/publications/st_space_49E.pdf')],
  },
  {
    id: 'lts-guidelines',
    number: '06',
    section: 'mitigation-rules',
    year: '2019',
    tabTitleZh: '长期可持续性指南',
    tabTitleEn: 'LTS Guidelines',
    typeLabelZh: '联合国指南｜非约束性',
    typeLabelEn: 'UN GUIDELINES · NON-BINDING',
    titleZh: '《外空活动长期可持续性指南》',
    titleEn: 'Guidelines for the Long-term Sustainability of Outer Space Activities',
    bodyZh: [
      'COPUOS 于 2019 年通过了 21 项《外空活动长期可持续性指南》。',
      '这些指南覆盖空间物体登记、联系信息共享、碰撞评估、设计与运行、国际合作、信息交换以及失控再入风险等内容。它们把碎片问题放入更大的轨道长期可持续使用框架中，但仍主要依赖各国主动落实。',
    ],
    bodyEn: [
      'COPUOS adopted 21 Guidelines for the Long-term Sustainability of Outer Space Activities in 2019.',
      'They cover areas such as registration, contact information, conjunction assessment, design and operation of space objects, international cooperation, information exchange, and risks from uncontrolled re-entry. They place space debris within the broader challenge of long-term sustainable use of orbit, but they remain voluntarily implemented guidelines.',
    ],
    highlightZh: '这些指南告诉各国“怎样更安全地长期使用轨道”，实施仍主要依赖各国主动落实。',
    highlightEn: 'They describe how States should use orbit more sustainably, but implementation still depends largely on national action.',
    sourceLinks: [source('UNOOSA — 长期可持续性指南', 'UNOOSA — LTS Guidelines', 'https://lts.unoosa.org/unoosa_lts/en/resources/guidelines/publication.html')],
  },
  {
    id: 'iadc-guidelines',
    number: '07',
    section: 'mitigation-rules',
    year: 'REV. 4 / 2025',
    tabTitleZh: 'IADC 减缓指南',
    tabTitleEn: 'IADC Guidelines',
    typeLabelZh: '机构间指南｜非约束性',
    typeLabelEn: 'IADC GUIDELINES · NON-BINDING',
    titleZh: 'IADC《空间碎片减缓指南》',
    titleEn: 'IADC Space Debris Mitigation Guidelines',
    bodyZh: [
      'IADC 由多个主要航天机构参与，是国际空间碎片技术协调的重要平台。其指南覆盖任务规划、碎片释放、碰撞风险、航天器与火箭级解体、任务后处置和再入风险等问题。',
      '截至 2026 年，IADC 官方文件库提供的现行版本为 Revision 4（2025）。IADC 技术工作影响广泛，但其本身不是全球执法机构。',
    ],
    bodyEn: [
      'The Inter-Agency Space Debris Coordination Committee (IADC) brings together major space agencies and serves as an important forum for technical coordination on orbital debris. Its Space Debris Mitigation Guidelines address mission planning, debris released during normal operations, collision risk, spacecraft and launch-stage break-ups, post-mission disposal, and re-entry risks.',
      'As of 2026, the IADC public repository lists Revision 4, issued in 2025. IADC work strongly influences international guidelines, national policies, and technical standards, but IADC itself is not a global enforcement authority.',
    ],
    highlightZh: 'IADC 提供重要技术共识，但它不是全球“太空交通警察”。',
    highlightEn: 'IADC builds technical consensus; it is not a global space-traffic police force.',
    sourceLinks: [source('IADC — 空间碎片减缓指南', 'IADC — Space Debris Mitigation Guidelines', 'https://www.iadc-home.org/documents_public')],
  },
  {
    id: 'iso-24113',
    number: '08',
    section: 'mitigation-rules',
    year: '2023',
    tabTitleZh: 'ISO 24113 标准',
    tabTitleEn: 'ISO 24113',
    typeLabelZh: '国际技术标准',
    typeLabelEn: 'INTERNATIONAL STANDARD',
    titleZh: 'ISO 24113:2023：把碎片减缓写进工程要求',
    titleEn: 'ISO 24113:2023: Turning Debris Mitigation into Engineering Requirements',
    bodyZh: [
      'ISO 24113:2023 是空间碎片减缓领域的重要国际技术标准。它针对进入或经过近地空间的无人空间系统，规定了航天器、运载火箭轨道级以及正常任务中释放物体需要考虑的主要碎片减缓要求。',
      '标准的意义在于把“少制造垃圾”落实到设计、运行和任务结束等工程环节。但 ISO 是国际标准，并不会因为发布就自动成为所有国家的国内法律。它通常需要被法规、许可证、机构规则、采购要求或合同采用，才能在具体项目中形成相应约束。',
    ],
    bodyEn: [
      'ISO 24113:2023 is a major international technical standard for space debris mitigation. It defines primary mitigation requirements for unmanned systems launched into or passing through near-Earth space, including spacecraft, launch-vehicle orbital stages, and objects released during normal operations.',
      'Its importance lies in translating debris mitigation into engineering requirements across design, operation, and end-of-life phases. However, an ISO standard does not automatically become national law everywhere. Its practical force often comes through adoption in regulations, licences, agency rules, procurement requirements, or contracts.',
    ],
    highlightZh: '国际标准很重要，但“ISO 标准”不等于“自动适用于全世界的法律”。',
    highlightEn: 'An international standard is influential, but it is not automatically a globally binding law.',
    sourceLinks: [source('ISO 24113:2023', 'ISO 24113:2023', 'https://www.iso.org/standard/83494.html')],
  },
  {
    id: 'esa-requirements',
    number: '09',
    section: 'mitigation-rules',
    year: '2023 / 2025',
    tabTitleZh: 'ESA 减缓要求',
    tabTitleEn: 'ESA Requirements',
    typeLabelZh: '机构要求｜适用于 ESA 相关活动',
    typeLabelEn: 'AGENCY REQUIREMENT · ESA SCOPE',
    titleZh: 'ESA《空间碎片减缓要求》：机构可以把标准变成项目硬要求',
    titleEn: 'ESA Space Debris Mitigation Requirements: Making Standards Operational',
    bodyZh: [
      'ESA 已建立专门的空间碎片减缓政策和技术要求，并将其用于 ESA 项目及相关活动。',
      '要求覆盖防止碎片释放、控制碰撞与解体风险、提高任务后轨道清除成功率以及安全再入等问题。这类机构要求可以通过项目审查、采购和合同机制直接进入任务执行，因此比单纯的自愿指南更具操作约束力。',
    ],
    bodyEn: [
      'ESA introduced a stricter Space Debris Mitigation Policy and Space Debris Mitigation Requirements in 2023 and continued updating the requirements in 2025.',
      'Within their scope, the requirements address debris release, break-up risk, collision risk, system-failure risk, orbital clearance, and safe re-entry. ESA has also tightened its own post-mission orbital-clearance target in protected low-Earth-orbit regions toward a five-year timescale.',
    ],
    highlightZh: '规则能否真正落地，很大程度取决于谁有权把它写进任务、合同和审查流程。',
    highlightEn: 'Rules become much stronger when an institution can put them directly into missions, contracts, and compliance reviews.',
    sourceLinks: [
      source('ESA — 空间碎片减缓', 'ESA — Space Debris Mitigation', 'https://technology.esa.int/page/space-debris-mitigation'),
    ],
  },
  {
    id: 'zero-debris-charter',
    number: '10',
    section: 'mitigation-rules',
    year: '2030 GOAL',
    tabTitleZh: 'Zero Debris Charter',
    tabTitleEn: 'Zero Debris',
    typeLabelZh: '自愿倡议｜非约束性',
    typeLabelEn: 'VOLUNTARY INITIATIVE · NON-BINDING',
    titleZh: 'Zero Debris Charter：共同目标，不是新的国际条约',
    titleEn: 'Zero Debris Charter: A Shared Goal, Not a New International Treaty',
    bodyZh: [
      'Zero Debris Charter 是全球航天界共同参与形成的自愿倡议，提出面向 2030 年的空间碎片减缓与治理原则和目标。',
      '它希望推动更高的空间可持续性共识，但 Charter 本身不是新的国际条约，也没有建立一个可以对所有参与者实施法律处罚的全球执法机构。',
    ],
    bodyEn: [
      'The Zero Debris Charter is a voluntary, community-driven initiative that sets shared principles and measurable ambitions for debris mitigation and remediation toward 2030.',
      'It is intended to build stronger space-sustainability commitments among agencies, companies, research institutions, and other space actors. The Charter itself is not a new international treaty and does not create a global enforcement authority with legal power over all participants.',
    ],
    highlightZh: 'Zero Debris Charter 是自愿承诺，不是一部新的全球太空垃圾法。',
    highlightEn: 'The Zero Debris Charter is a voluntary commitment, not a new global debris law.',
    sourceLinks: [
      source('ESA — Zero Debris Charter', 'ESA — The Zero Debris Charter', 'https://www.esa.int/Space_Safety/Clean_Space/The_Zero_Debris_Charter'),
    ],
  },
  {
    id: 'fcc-five-year-rule',
    number: '11',
    section: 'regulation',
    year: '2022',
    tabTitleZh: 'FCC 五年处置规则',
    tabTitleEn: 'FCC 5-Year Rule',
    typeLabelZh: '国内监管｜可依法执行',
    typeLabelEn: 'NATIONAL REGULATION · ENFORCEABLE WITHIN SCOPE',
    titleZh: '美国 FCC：把“5 年处置”写进监管规则',
    titleEn: 'U.S. FCC: Turning Five-Year Disposal into a Regulatory Requirement',
    bodyZh: [
      '美国 FCC 在 2022 年通过了新的卫星任务后处置规则。',
      '对于 FCC 规则适用范围内、任务结束时位于或经过 2,000 km 以下低地球轨道，并计划通过非受控大气再入完成处置的相关空间站，处置应尽快完成，原则上不得晚于任务结束后 5 年。这类国内监管展示了一种重要路径：国际碎片减缓原则可以通过许可证和国内规则转化为对具体运营者可执行的要求。',
    ],
    bodyEn: [
      'In 2022, the U.S. Federal Communications Commission adopted a new post-mission disposal rule.',
      'For space stations within the scope of FCC rules that end their missions in, or pass through, the low-Earth-orbit region below 2,000 km and plan disposal through uncontrolled atmospheric re-entry, disposal must be completed as soon as practicable and no later than five years after the end of mission. This illustrates how international mitigation principles can become enforceable operator requirements through national licensing and regulation.',
    ],
    highlightZh: '国家许可证和国内法规，可以把国际“建议”转化为具体运营要求。',
    highlightEn: 'National licences and regulations can turn international recommendations into concrete operator requirements.',
    sourceLinks: [
      source('FCC — 5 年规则', 'FCC — Five-Year Rule', 'https://www.fcc.gov/document/fcc-adopts-new-5-year-rule-deorbiting-satellites'),
    ],
  },
  {
    id: 'uk-spaceflight-licensing',
    number: '12',
    section: 'regulation',
    year: '2018 / 2021',
    tabTitleZh: '英国空间活动许可',
    tabTitleEn: 'UK Licensing',
    typeLabelZh: '国内监管｜可依法执行',
    typeLabelEn: 'NATIONAL REGULATION · ENFORCEABLE WITHIN SCOPE',
    titleZh: '英国：通过空间活动许可证落实碎片减缓',
    titleEn: 'United Kingdom: Implementing Debris Mitigation through Spaceflight Licensing',
    bodyZh: [
      '英国通过《Space Industry Act 2018》《Space Industry Regulations 2021》以及 CAA 的航天许可制度监管空间活动。',
      '英国法规要求相关运营者采取合理措施减少对轨道环境的不利影响，其中可以包括避免释放空间碎片、降低碰撞风险，以及在任务生命周期中考虑碎片减缓措施。英国 CAA 的轨道运营许可范围也可以覆盖在轨服务、制造和主动碎片清除等活动。',
    ],
    bodyEn: [
      'The United Kingdom regulates space activities through the Space Industry Act 2018, the Space Industry Regulations 2021, and the Civil Aviation Authority’s licensing framework.',
      'Operators are expected to take reasonable steps to reduce adverse effects on the orbital environment. Measures can include avoiding debris release, reducing collision risk, and integrating debris mitigation into mission planning and operations. CAA orbital operator licences can also cover activities such as in-orbit servicing, manufacturing, and active debris removal.',
    ],
    highlightZh: '主动清理本身也可能需要授权和许可；“清垃圾”并不意味着可以绕开监管。',
    highlightEn: 'Active debris removal can itself require authorization and licensing; “cleaning up” does not bypass regulation.',
    sourceLinks: [
      source('UK CAA — 立法', 'UK CAA — Legislation', 'https://www.caa.co.uk/space/about-the-space-team/legislation/'),
    ],
  },
  {
    id: 'eu-space-act',
    number: '13',
    section: 'regulation',
    year: 'PROPOSAL',
    tabTitleZh: 'EU Space Act 提案',
    tabTitleEn: 'EU Space Act',
    typeLabelZh: '立法提案｜尚未生效',
    typeLabelEn: 'LEGISLATIVE PROPOSAL · NOT YET IN FORCE',
    titleZh: 'EU Space Act：欧洲正在尝试统一规则',
    titleEn: 'EU Space Act: Europe Is Working toward More Unified Rules',
    bodyZh: [
      '欧盟委员会于 2025 年提出 EU Space Act，希望在欧盟层面建立更加统一的空间活动框架，重点涉及空间安全、韧性和可持续性，并包含空间碎片相关要求。',
      '截至 2026 年 8 月，EU Space Act 仍处于欧洲议会和欧盟理事会的普通立法程序谈判阶段，并不是已经生效的欧盟法律。因此网站不能把它标记成“现行欧盟太空法”。',
    ],
    bodyEn: [
      'The European Commission proposed the EU Space Act in 2025 to create a more harmonized EU framework for space activities, focusing on safety, resilience, and sustainability, including space-debris-related requirements.',
      'As of August 2026, the proposal is still being negotiated by the European Parliament and the Council under the ordinary legislative procedure. It is not yet an EU law in force. The website must therefore not present it as an existing, fully enacted “EU Space Law.”',
    ],
    highlightZh: 'EU Space Act 目前仍是立法提案，不能写成已经生效的法律。',
    highlightEn: 'The EU Space Act is still a legislative proposal and must not be presented as law already in force.',
    sourceLinks: [source('欧盟委员会 — EU Space Act', 'European Commission — EU Space Act', 'https://defence-industry-space.ec.europa.eu/eu-space-act_en')],
  },
  {
    id: 'global-regulation',
    number: '14',
    section: 'regulation',
    year: '2026',
    tabTitleZh: '全球监管差异',
    tabTitleEn: 'Regulatory Differences',
    typeLabelZh: '监管现状',
    typeLabelEn: 'REGULATORY LANDSCAPE',
    titleZh: '全球监管现状：每个国家落实规则的方式并不一样',
    titleEn: 'Global Regulation: Countries Implement Debris Rules Differently',
    bodyZh: [
      '今天并不存在一部覆盖所有国家、所有运营者、所有碎片问题的“全球太空垃圾法典”。',
      '各国会通过航天法、许可证、机构要求、技术标准或运营条件，把国际条约和碎片减缓指南转化为本国的监管制度。UNOOSA 持续维护《Space Debris Mitigation Standards Compendium》，汇总各国和国际组织采用的碎片减缓标准。2026 年的最新汇编仍显示，各地采用的制度、标准和实施方式存在明显差异。',
    ],
    bodyEn: [
      'There is no single global “space debris code” that governs every State, operator, and debris problem in the same way.',
      'States implement treaty obligations and mitigation guidelines through combinations of national space law, licensing, agency requirements, technical standards, and operating conditions. UNOOSA maintains the Space Debris Mitigation Standards Compendium, which documents standards adopted by States and international organizations. The 2026 compilation continues to show significant differences in regulatory approaches and implementation.',
    ],
    highlightZh: '今天更接近“国际原则 + 各国实施”，而不是“一部全球统一的太空垃圾法”。',
    highlightEn: 'Today’s system is closer to “international principles + national implementation” than one unified global debris law.',
    sourceLinks: [
      source('UNOOSA — 减缓标准汇编', 'UNOOSA — Space Debris Mitigation Standards Compendium', 'https://www.unoosa.org/oosa/en/ourwork/topics/space-debris/compendium.html'),
    ],
  },
  {
    id: 'global-cleanup-gap',
    number: '15',
    section: 'governance-gaps',
    year: 'CORE',
    tabTitleZh: '全球清理机制缺口',
    tabTitleEn: 'Global Cleanup Gap',
    typeLabelZh: '治理问题｜核心知识',
    typeLabelEn: 'GOVERNANCE GAP · CORE KNOWLEDGE',
    titleZh: '有规则，但缺少全球统一的强制清理机制',
    titleEn: 'Rules Exist, but There Is No Unified Global Compulsory Cleanup Mechanism',
    bodyZh: [
      '现有国际条约已经建立了国家责任、空间物体登记和损害赔偿制度。联合国、IADC、ISO、ESA 和各国监管机构也已经形成大量空间碎片减缓规则。',
      '但这些制度没有建立一个全球“太空环卫机构”，也没有形成一套普遍适用于所有国家的历史碎片强制清理制度。',
    ],
    bodyEn: [
      'International treaties already establish frameworks for state responsibility, registration, and liability. The UN, IADC, ISO, ESA, and national regulators have also developed extensive debris-mitigation rules.',
      'However, these frameworks have not created a global “space sanitation authority” or a universally applicable system compelling States to remove all legacy debris.',
    ],
    highlightZh: '目前没有一套全球统一、普遍适用且具有强制执行力的机制，可以要求各国普遍清除其既有失效空间物体；同时，也不存在一项普遍规则，允许其他国家或运营者未经授权和协调就直接清除他国登记的失效空间物体。',
    highlightEn: 'There is currently no single, universally applicable and globally enforceable mechanism that generally compels States to remove their existing defunct space objects. Nor is there a universal rule allowing another State or operator to remove a foreign registered space object without authorization and coordination.',
    sourceLinks: [
      source('UNOOSA — 空间法条约', 'UNOOSA — Space Law Treaties', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties.html'),
    ],
  },
  {
    id: 'removal-authorization',
    number: '16',
    section: 'governance-gaps',
    year: 'AUTHORITY',
    tabTitleZh: '报废卫星清理授权',
    tabTitleEn: 'Removal Authority',
    typeLabelZh: '治理问题',
    typeLabelEn: 'GOVERNANCE GAP',
    titleZh: '谁能处理一颗属于其他国家的报废卫星？',
    titleEn: 'Who Can Handle a Defunct Satellite Belonging to Another Country?',
    bodyZh: [
      '从工程角度看，主动碎片清除可能意味着靠近、捕获、拖曳或改变一颗失效卫星的轨道。',
      '但从法律角度看，报废卫星并不会自动失去登记、管辖或所有权关系。因此，如果清理对象属于另一个国家登记的空间物体，就需要处理授权、管辖、所有权、责任以及国家间协调等问题。',
    ],
    bodyEn: [
      'From an engineering perspective, active debris removal may involve approaching, capturing, towing, or changing the orbit of a defunct spacecraft.',
      'Legally, however, a defunct satellite does not automatically lose its registration, jurisdictional link, or ownership status. Removing a space object registered by another State therefore raises issues of authorization, jurisdiction, ownership, liability, and international coordination.',
    ],
    highlightZh: '“没人再用”不等于“谁都可以拿走”。',
    highlightEn: '“No longer in use” does not mean “free for anyone to remove.”',
    sourceLinks: [source('UNOOSA —《外层空间条约》第 VIII 条', 'UNOOSA — Outer Space Treaty, Article VIII', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/outerspacetreaty.html')],
  },
  {
    id: 'collision-attribution',
    number: '17',
    section: 'governance-gaps',
    year: 'LIABILITY',
    tabTitleZh: '碰撞责任认定',
    tabTitleEn: 'Collision Liability',
    typeLabelZh: '治理问题',
    typeLabelEn: 'GOVERNANCE GAP',
    titleZh: '有责任规则，也不代表每次碰撞都容易追责',
    titleEn: 'Liability Rules Exist, but Attribution Can Still Be Difficult',
    bodyZh: [
      '《责任公约》已经为不同类型的空间物体损害建立责任框架。',
      '但对于发生在外层空间的空间物体损害，责任可能涉及过错判断。如果碎片来源难以确认、涉及多个物体或多个行为主体，因果关系和过错认定都会更加复杂。',
    ],
    bodyEn: [
      'The Liability Convention provides a legal framework for different forms of damage caused by space objects.',
      'For damage occurring in outer space, liability may depend on fault. In practice, events involving uncertain debris origin, multiple objects, or multiple actors can make causation and fault much more difficult to establish. Liability law therefore cannot replace debris tracking, conjunction assessment, collision avoidance, and prevention.',
    ],
    highlightZh: '“法律可以追责”不等于“每一次太空碰撞都能轻松确定谁负责”。',
    highlightEn: 'Having a liability framework does not mean responsibility for every orbital collision is easy to establish.',
    sourceLinks: [source('UNOOSA —《责任公约》', 'UNOOSA — Liability Convention', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties/introliability-convention.html')],
  },
  {
    id: 'prevention-versus-remediation',
    number: '18',
    section: 'governance-gaps',
    year: 'LEGACY',
    tabTitleZh: '新垃圾与旧垃圾治理',
    tabTitleEn: 'Prevention vs Removal',
    typeLabelZh: '治理问题',
    typeLabelEn: 'GOVERNANCE GAP',
    titleZh: '现有规则更擅长减少新垃圾，而非清理历史碎片',
    titleEn: 'Today’s Rules Are Better at Preventing New Debris than Cleaning Up Old Debris',
    bodyZh: [
      'COPUOS、IADC、ISO、ESA 以及许多国家监管规则，重点都放在减少新的碎片产生：限制任务中释放物体、避免碰撞和爆炸、做好钝化、提高任务后处置成功率。',
      '已经存在几十年的废弃卫星、火箭级和历史碎片，则需要主动清除或其他补救措施。这类任务还会遇到目标所有权、行动授权、责任承担和清理费用由谁承担等制度问题。',
    ],
    bodyEn: [
      'Many COPUOS, IADC, ISO, ESA, and national rules focus primarily on preventing new debris: limiting mission-related releases, avoiding collisions and break-ups, passivating spacecraft, and improving post-mission disposal.',
      'Legacy satellites, rocket bodies, and historical debris already in orbit may require active removal or other remediation measures. Those missions require not only technical capability but also solutions for ownership, authorization, liability, and who pays for removal.',
    ],
    highlightZh: '“防止产生新垃圾”和“清理已经存在的旧垃圾”，是两个不同的治理问题。',
    highlightEn: 'Preventing new debris and removing legacy debris are two different governance problems.',
    sourceLinks: [
      source('ESA — 主动碎片清除', 'ESA — Active Debris Removal', 'https://www.esa.int/Space_Safety/Space_Debris/Active_debris_removal'),
    ],
  },
]

export const LEGAL_SUMMARY = {
  id: 'legal-framework-summary',
  section: 'conclusion',
  year: 'CONCLUSION',
  tabTitleZh: '法律结论',
  tabTitleEn: 'Legal Takeaways',
  titleZh: '现在的法律，到底解决了什么？',
  titleEn: 'What Does Today’s Legal Framework Actually Solve?',
  establishedTitleZh: '已经建立的框架',
  establishedTitleEn: 'What already exists',
  establishedZh: [
    { title: '国家有责任。', body: '国家需要对本国空间活动承担国际责任，并对非政府实体实施授权和持续监督。' },
    { title: '空间物体可以登记。', body: '登记制度帮助确认空间物体的身份和登记国。' },
    { title: '造成损害有责任框架。', body: '《责任公约》规定了空间物体造成损害后的国际责任和赔偿框架。' },
    { title: '减少新垃圾已经有大量规则。', body: 'COPUOS、IADC、ISO、ESA 和各国监管体系已经形成较成熟的碎片减缓框架。' },
  ],
  establishedEn: [
    { title: 'States have responsibilities.', body: 'States bear international responsibility for national space activities and must authorize and continuously supervise non-governmental space activities.' },
    { title: 'Space objects can be registered.', body: 'Registration systems help identify space objects and their States of registry.' },
    { title: 'There is a liability framework for damage.', body: 'The Liability Convention establishes international rules for responsibility and compensation when space objects cause damage.' },
    { title: 'There are extensive rules for preventing new debris.', body: 'COPUOS, IADC, ISO, ESA, and national regulatory systems have created a substantial debris-mitigation framework.' },
  ],
  unresolvedTitleZh: '仍未解决的问题',
  unresolvedTitleEn: 'What remains unresolved',
  highlightZh: '今天仍没有一套全球统一、普遍适用且具有强制执行力的制度，能够一次性解决“谁必须清理历史碎片、谁有权清理、如何跨国执行、费用由谁承担”等全部问题。',
  highlightEn: 'There is still no single, universally applicable and globally enforceable system that resolves all questions of who must remove legacy debris, who is authorized to remove it, how obligations can be enforced across borders, and who pays for cleanup.',
  closingZh: '太空垃圾治理真正缺少的，并不是“完全没有规则”，而是规则之间的衔接、执行能力，以及面向既有碎片的全球协调机制。',
  closingEn: 'The problem is not that space debris is completely unregulated. The deeper challenge is coordination between rules, effective implementation, and global mechanisms for dealing with debris that already exists.',
}

export const LEGAL_SOURCE_INDEX = [
  {
    id: 'unoosa-treaties',
    number: '01',
    tabTitleZh: '空间法条约',
    tabTitleEn: 'Space Law Treaties',
    titleZh: 'UNOOSA — 空间法条约',
    titleEn: 'UNOOSA — Space Law Treaties',
    descriptionZh: '国际空间法五大联合国条约官方入口。',
    descriptionEn: 'Official entry point for the five United Nations treaties on outer space.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://www.unoosa.org/oosa/en/ourwork/spacelaw/treaties.html')],
  },
  {
    id: 'copuos-mitigation',
    number: '02',
    titleZh: 'UNOOSA — 空间碎片减缓准则',
    titleEn: 'UNOOSA — Space Debris Mitigation Guidelines',
    descriptionZh: 'COPUOS 空间碎片减缓准则官方文本。',
    descriptionEn: 'Official text of the COPUOS Space Debris Mitigation Guidelines.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://www.unoosa.org/pdf/publications/st_space_49E.pdf')],
  },
  {
    id: 'lts',
    number: '03',
    titleZh: 'UNOOSA — 长期可持续性指南',
    titleEn: 'UNOOSA — Long-term Sustainability Guidelines',
    descriptionZh: '21 项外空活动长期可持续性指南官方文本。',
    descriptionEn: 'Official text of the 21 Long-term Sustainability Guidelines.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://lts.unoosa.org/unoosa_lts/en/resources/guidelines/publication.html')],
  },
  {
    id: 'compendium',
    number: '04',
    titleZh: 'UNOOSA — 空间碎片减缓标准汇编',
    titleEn: 'UNOOSA — Space Debris Mitigation Standards Compendium',
    descriptionZh: '各国与国际组织空间碎片减缓标准汇编。',
    descriptionEn: 'Compendium of debris-mitigation standards adopted by States and international organizations.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://www.unoosa.org/oosa/en/ourwork/topics/space-debris/compendium.html')],
  },
  {
    id: 'iadc',
    number: '05',
    titleZh: 'IADC — 官方文件库',
    titleEn: 'IADC — Public Documents',
    descriptionZh: 'IADC 空间碎片指南与技术文件官方库。',
    descriptionEn: 'Official library of IADC debris guidelines and technical documents.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://www.iadc-home.org/documents_public')],
  },
  {
    id: 'iso-24113',
    number: '06',
    titleZh: 'ISO 24113:2023',
    titleEn: 'ISO 24113:2023',
    descriptionZh: '空间碎片减缓主要国际技术标准。',
    descriptionEn: 'Major international technical standard for space debris mitigation.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://www.iso.org/standard/83494.html')],
  },
  {
    id: 'esa-mitigation',
    number: '07',
    titleZh: 'ESA — 空间碎片减缓',
    titleEn: 'ESA — Space Debris Mitigation',
    descriptionZh: 'ESA 空间碎片减缓政策、要求与相关技术文件。',
    descriptionEn: 'ESA debris-mitigation policy, requirements, and related technical documents.',
    links: [source('查看官方来源', 'OFFICIAL SOURCE', 'https://technology.esa.int/page/space-debris-mitigation')],
  },
  {
    id: 'national-regional',
    number: '08',
    titleZh: '国内与区域监管',
    titleEn: 'National / Regional Regulation',
    descriptionZh: '美国 FCC、英国 CAA 与 EU Space Act 官方入口。',
    descriptionEn: 'Official sources for the U.S. FCC, UK CAA, and EU Space Act.',
    links: [
      source('FCC', 'FCC', 'https://www.fcc.gov/space/faq-orbital-debris'),
      source('UK CAA', 'UK CAA', 'https://www.caa.co.uk/space/about-the-space-team/legislation/'),
      source('EU Space Act', 'EU Space Act', 'https://defence-industry-space.ec.europa.eu/eu-space-act_en'),
    ],
  },
]
